# 服务器前置任务(ubuntu使用)
- name: lamp
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt-get -y install python
  ignore_errors: yes


# 核心任务

- name: lamp
  hosts: all
  become: yes
  become_method: sudo
  vars_prompt:
  

  roles:
    - { role: common , tags: "common"}  
    - {role: apache, tags: "apache"}
    - { role: mysql , tags: "mysql"}
    - { role: php-fpm , tags: "php-fpm"}
    - { role: lamp , tags: "lamp"}
    - {role: phpmyadmin, tags: "phpmyadmin"}
    - {role: 9panel, tags: "9panel"}
    - {role: inotify_watch, tags: "inotify_watch"}



    


                                                                                                    