# 核心任务
- name: main
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: 'php_choose'
      prompt: "Choose serial number to install PHP \n
      1: PHP 5.6\n
      2: PHP 7.0\n
      3: PHP 7.1\n
      4: PHP 7.2\n
      5: PHP 7.3\n
      6: PHP 7.4\n"
      private: no
      default: 4

    - name: 'mysql_choose'
      prompt: "Choose serial number to install MySQL \n
      1: MySQL 5.5(not support Ubuntu)\n
      2: MySQL 5.6(not support Ubuntu)\n
      3: MySQL 5.7\n
      4: MySQL 8.0(not support CentOS)\n"
      private: no
      default: 2  

  vars:
    mysql_ver:
      '1': 5.5
      '2': 5.6
      '3': 5.7
      '4': 8.0
    php_ver:
      '1': 5.6
      '2': 7.0
      '3': 7.1
      '4': 7.2
      '5': 7.3
    mysql_version: "{{mysql_ver[mysql_choose]}}"

    phpver: "{{php_ver[php_choose]}}"

  roles:
    - role: role_common
    - role: role_cloud
    - role: role_apache
    - role: role_mysql
    - role: role_php-fpm
    - role: role_lamp
    - role: role_init_password
    - role: role_phpmyadmin
    - role: role_9panel
    - role: role_inotify_watch
    - role: role_end
