# 核心任务
- name: lamp
  hosts: all
  become: yes
  become_method: sudo
  vars_prompt:
    - name: 'php_choose'
      prompt: "Choose serial number to install PHP \n
      1: PHP 5.6\n
      2: PHP 7.0\n
      3: PHP 7.1\n
      4: PHP 7.2 (default)\n
      5: PHP 7.3\n"
      private: no
      default: 4

    - name: 'mysql_choose'
      prompt: "Choose serial number to install MySQL \n
      1: MySQL 5.5\n
      2: MySQL 5.6 (default)\n
      3: MySQL 5.7\n"
      private: no
      default: 2  

  vars:
    mysql_ver:
      '1': '5.5'
      '2': '5.6'
      '3': '5.7'
    php_ver:
      '1': '5.6'
      '2': '7.0'
      '3': '7.1'
      '4': '7.2'
      '5': '7.3'
    mysqlver: "{{mysql_ver[mysql_choose]}}"

    phpver: "{{php_ver[php_choose]}}"


  
  roles:
    - {role: common , tags: "common"}  
    - {role: cloud , tags: "cloud"}  
    - {role: apache, tags: "apache"}
    - {role: mysql , tags: "mysql"}
    - {role: php-fpm , tags: "php-fpm"}
    - {role: lamp , tags: "lamp"}
    - {role: phpmyadmin, tags: "phpmyadmin"}
    - {role: 9panel, tags: "9panel"}
    - {role: inotify_watch, tags: "inotify_watch"}
    - {role: end, tags: 'end'}



    


                                                                                                    
